version : "3.3"
services :
    web :
      container_name : "web-flask-ctr"
      build : .
      ports :
          - 8888:8888

    db :
       container_name : "web-flask-db"
       image : mysql:latest
       ports :
          - 3306:3306
       environment :
          - "MYSQL_ROOT_PASSWORD:PASSWORD"

